% ---- Adrian Lindsey ------------------------- %
% ---- HW 3 ----------------------------------- %
% ---- Problem 2 ------------------------------ %
% ---- Test ----------------------------------- %

function test_quad_forms(a)

      % This plots the surface generated by taking matrix A
      % as a quadratic form.  A is assumed 2x2

      [x, y] = meshgrid(-5:1:5, -5:1:5);
      s = size(x);

      f = zeros(s);  % Preallocate f to be same size as x
      for i = 1:length(x)
          for j = 1:length(y)
              f(i,j) = quad_forms(a, x(i, j), y(i, j));

          end
      end
      
     
      
      surf(x, y, f);

end